FROM ubuntu:xenial

RUN apt-get -y update && \
    apt-get -y install build-essential git wget python python-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN apt-get update && \
    apt-get install -y octave octave-io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install oct2py

RUN apt-get -y update && \
    apt-get -y install python-numpy python-scipy && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ADD src /src

RUN mkdir tasbe

RUN cd tasbe
RUN wget https://github.com/jegentile/TASBEFlowAnalytics/archive/master.zip
RUN unzip master.zip
RUN cd /TASBEFlowAnalytics-master && \
    make install && cd ../ && \
    rm -rf master.zip

CMD python /src/fc.py --config $CONFIG --octave-method-path /src/
